title: Alex Fraga percussion
description: "Learn authentic drumming and hand percussion from an experienced instructor in Toronto."
baseurl: "" # leave blank if using custom domain at root
url: "https://www.alexfragapercussion.com"
theme: minima
